import speechTexts from './speech-allowlist.json';
const encoder=new TextEncoder(),decoder=new TextDecoder();
const b64=bytes=>{let s='';for(let i=0;i<bytes.length;i+=8192)s+=String.fromCharCode(...bytes.subarray(i,i+8192));return btoa(s);};
const bytes=s=>Uint8Array.from(atob(s),c=>c.charCodeAt(0));
const url64=b=>b64(b).replace(/\+/g,'-').replace(/\//g,'_').replace(/=+$/,'');
const from64=s=>bytes(s.replace(/-/g,'+').replace(/_/g,'/')+'='.repeat((4-s.length%4)%4));
const sha=async text=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',encoder.encode(text))),b=>b.toString(16).padStart(2,'0')).join('');
function response(req,env,status,body,extra={}){const origin=req.headers.get('Origin')||'',headers={'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Vary':'Origin','X-Content-Type-Options':'nosniff',...extra};if(env.ALLOWED_ORIGINS.split(',').includes(origin))headers['Access-Control-Allow-Origin']=origin;return new Response(status===204?null:JSON.stringify(body),{status,headers});}
function allowed(env,name){return typeof name==='string'&&/^[a-z][a-z0-9_-]{1,31}$/.test(name)&&env.ALLOWED_ACCOUNTS.split(',').includes(name);}
async function key(env){return crypto.subtle.importKey('raw',encoder.encode(env.SESSION_SECRET),{name:'HMAC',hash:'SHA-256'},false,['sign','verify']);}
async function session(env,username){const part=url64(encoder.encode(JSON.stringify({username,exp:Math.floor(Date.now()/1000)+604800})));const sig=new Uint8Array(await crypto.subtle.sign('HMAC',await key(env),encoder.encode(part)));return part+'.'+url64(sig);}
async function identify(req,env){try{const token=(req.headers.get('Authorization')||'').replace(/^Bearer /,''),[part,sig]=token.split('.');if(!part||!sig)return null;if(!await crypto.subtle.verify('HMAC',await key(env),from64(sig),encoder.encode(part)))return null;const p=JSON.parse(decoder.decode(from64(part)));return allowed(env,p.username)&&p.exp>Date.now()/1000?p.username:null;}catch{return null;}}
async function github(env,path,options={}){const r=await fetch('https://api.github.com/repos/'+env.GITHUB_REPO+'/contents/'+path,{...options,headers:{Accept:'application/vnd.github+json','Authorization':'Bearer '+env.GITHUB_TOKEN,'User-Agent':'Lixia-Typing-Garden-V1','X-GitHub-Api-Version':'2022-11-28',...(options.headers||{})}});if(r.status===404&&!options.method)return null;if(!r.ok){const e=new Error(r.status===409||r.status===422?'conflict':'github-unavailable');e.status=r.status;throw e;}return r.json();}
async function read(env,username){const r=await github(env,'accounts/'+username+'/state.json?ref='+env.GITHUB_BRANCH);if(!r)return {username,state:null,revision:null,updatedAt:null};const record=r.content?JSON.parse(decoder.decode(bytes(r.content.replace(/\s/g,'')))):await github(env,'accounts/'+username+'/state.json?ref='+env.GITHUB_BRANCH,{headers:{Accept:'application/vnd.github.raw+json'}});return {username,state:record.state,revision:r.sha,updatedAt:record.updatedAt||null,version:'1.0.0'};}
async function body(req,max=2*1024*1024){if(Number(req.headers.get('Content-Length')||0)>max)throw Error('too-large');const text=await req.text();if(encoder.encode(text).length>max)throw Error('too-large');return JSON.parse(text);}
function validState(s){return s&&s.version===1&&typeof s==='object'&&!Array.isArray(s)&&typeof s.completions==='object'&&Array.isArray(s.sessions)&&Array.isArray(s.flowerEvents)&&typeof s.settings==='object'&&Array.isArray(s.exams)&&Array.isArray(s.rankings)&&typeof s.growth==='object'&&Number.isFinite(s.flowers)&&s.flowers>=0&&s.sessions.length<=500&&s.flowerEvents.length<=4000&&s.exams.length<=100&&s.rankings.length<=100;}
const recent=new Map();function limit(name,kind,max){const id=name+':'+kind,now=Date.now();let v=recent.get(id);if(!v||v.time<now-60000){v={time:now,count:0};recent.set(id,v);}v.count++;return v.count<=max;}
export default {async fetch(req,env,ctx){const url=new URL(req.url),origin=req.headers.get('Origin')||'';
 if(origin&&!env.ALLOWED_ORIGINS.split(',').includes(origin))return response(req,env,403,{error:'此来源未获允许'});
 if(req.method==='OPTIONS')return response(req,env,204,null,{'Access-Control-Allow-Methods':'GET,POST,PUT,OPTIONS','Access-Control-Allow-Headers':'Content-Type,Authorization','Access-Control-Max-Age':'86400'});
 if(url.pathname==='/health')return response(req,env,200,{ok:true,version:'1.0.0',storage:'GitHub private repository'});
 try{
  if(url.pathname==='/session'&&req.method==='POST'){const b=await body(req,4096);if(!allowed(env,b.username))return response(req,env,403,{error:'账号名不正确，请重新输入。'});if(!limit(req.headers.get('CF-Connecting-IP')||'local','login',30))return response(req,env,429,{error:'操作太快，请稍后重试。'});return response(req,env,200,{username:b.username,token:await session(env,b.username),...(await read(env,b.username))});}
  if(url.pathname.startsWith('/voice/')&&req.method==='GET'&&/^\/voice\/[a-f0-9]{64}\.wav$/.test(url.pathname)){const cached=await caches.default.match(new Request(url.origin+url.pathname));return cached||response(req,env,404,{error:'语音尚未生成，请重新试听。'});}
  const username=await identify(req,env);if(!username)return response(req,env,401,{error:'请先输入账号名。'});
  if(url.pathname==='/state'&&req.method==='GET')return response(req,env,200,await read(env,username));
  if(url.pathname==='/state'&&req.method==='PUT'){if(!limit(username,'save',12))return response(req,env,429,{error:'记录同步过于频繁，稍后会自动重试。'});const b=await body(req);if(!validState(b.state))return response(req,env,400,{error:'练习记录格式不正确。'});const current=await read(env,username);if((b.revision||null)!==(current.revision||null))return response(req,env,409,{error:'另一台设备更新了记录，正在合并。',...current});const updatedAt=new Date().toISOString(),record={version:'1.0.0',username,updatedAt,state:b.state};const result=await github(env,'accounts/'+username+'/state.json',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({message:'Save '+username+' typing progress · V1.0',branch:env.GITHUB_BRANCH,content:b64(encoder.encode(JSON.stringify(record,null,2))),...(current.revision?{sha:current.revision}:{})})});return response(req,env,200,{ok:true,username,revision:result.content.sha,updatedAt,version:'1.0.0'});}
  if(url.pathname==='/tts'&&req.method==='POST'){const b=await body(req,4096);if(typeof b.text!=='string'||!speechTexts.includes(b.text))return response(req,env,400,{error:'此讲解不在 V1.0 语音范围内。'});const hash=await sha(b.text),cacheKey=new Request(url.origin+'/voice/'+hash+'.wav'),cached=await caches.default.match(cacheKey);if(!cached){if(!limit(username,'voice',20))return response(req,env,429,{error:'语音正在准备，请稍后再听。'});const r=await fetch(env.MIMO_BASE_URL+'/chat/completions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+env.MIMO_API_KEY},body:JSON.stringify({model:'mimo-v2.5-tts',messages:[{role:'user',content:'温柔清晰的成年女性普通话老师，给小学三年级的小朋友讲解，语速自然。'},{role:'assistant',content:b.text}],audio:{format:'wav',voice:'茉莉'}}),signal:AbortSignal.timeout(60000)});if(!r.ok)return response(req,env,503,{error:'MiMo 语音暂时繁忙，请稍后重试。'});const j=await r.json(),audio=j.choices?.[0]?.message?.audio?.data;if(!audio)return response(req,env,503,{error:'暂时没有语音返回。'});await caches.default.put(cacheKey,new Response(bytes(audio),{headers:{'Content-Type':'audio/wav','Cache-Control':'public, max-age=2592000','Access-Control-Allow-Origin':'*'}}));}return response(req,env,200,{url:url.origin+'/voice/'+hash+'.wav',provider:'MiMo'});}
  return response(req,env,404,{error:'页面不存在。'});
 }catch(e){if(e.message==='conflict'){try{return response(req,env,409,{error:'记录已更新，请合并后重试。',...(await read(env,await identify(req,env)))});}catch{}}return response(req,env,e.message==='too-large'?413:503,{error:e.message==='too-large'?'记录文件过大，请先备份。':'云端暂时不可用，本机记录仍会保留。'});}
}};
