(() => {
 'use strict';const LOCAL='lixia-typing-garden-v1',base=new URL('.',location.href);let config,token,username,revision=null,latest=null,lastSaved='',dirty=false,saving=false,timer,lastWrite=0,checkpoint='',started=false,replaceRequested=false;
 const cacheKey=()=>LOCAL+':'+username,pendingKey=()=>LOCAL+':pending:'+username;
 function merge(a,b){if(!a)return b;if(!b)return a;const out=structuredClone(b);const max=(x,y)=>Math.max(Number(x)||0,Number(y)||0);out.version=1;out.guideSeen=!!(a.guideSeen||b.guideSeen);out.flowers=max(a.flowers,b.flowers);out.lastLesson=a.lastLesson||b.lastLesson;out.settings={...b.settings,...a.settings};
  for(const field of ['completions','keyStats','daily']){out[field]={};for(const key of new Set([...Object.keys(a[field]||{}),...Object.keys(b[field]||{})])){if(['__proto__','constructor','prototype'].includes(key))continue;const x=a[field]?.[key]||{},y=b[field]?.[key]||{};out[field][key]={...y,...x};for(const property of new Set([...Object.keys(x),...Object.keys(y)]))if(typeof x[property]==='number'||typeof y[property]==='number')out[field][key][property]=max(x[property],y[property]);}}
  out.growth={};for(const type of ['correct','pinyin','english','codes']){out.growth[type]={};for(const key of new Set([...Object.keys(a.growth?.[type]||{}),...Object.keys(b.growth?.[type]||{})]))if(!['__proto__','constructor','prototype'].includes(key))out.growth[type][key]=max(a.growth?.[type]?.[key],b.growth?.[type]?.[key]);}
  for(const [field,cap]of [['sessions',500],['flowerEvents',4000],['exams',100],['rankings',100]]){const map=new Map();for(const v of [...(b[field]||[]),...(a[field]||[])])map.set(field==='flowerEvents'?v.id:JSON.stringify(v),v);out[field]=[...map.values()].sort((x,y)=>String(x.date||'').localeCompare(String(y.date||''))).slice(-cap);}out.flowers=Math.max(out.flowers,out.flowerEvents.length);out.spelling={correct:max(a.spelling?.correct,b.spelling?.correct),sessions:max(a.spelling?.sessions,b.spelling?.sessions)};return out;
 }
 function status(message,kind='pending'){const el=document.getElementById('cloud-status');if(el){el.textContent=message;el.dataset.kind=kind;}}
 async function request(path,options={}){const r=await fetch(config.apiBase+path,{...options,headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{}),...(options.headers||{})}});const j=await r.json();if(!r.ok){const e=new Error(j.error||'云端暂时无法连接。');e.status=r.status;e.record=j;throw e;}return j;}
 function observe(state,{replace=false}={}){if(!started)return;if(replace){replaceRequested=true;localStorage.setItem(LOCAL+':replace:'+username,'true');}latest=structuredClone(state);dirty=JSON.stringify(latest)!==lastSaved;localStorage.setItem(pendingKey(),String(dirty));const next=[Object.keys(state.completions||{}).length,state.exams?.length,state.rankings?.length,state.spelling?.sessions].join(':');const urgent=checkpoint&&checkpoint!==next;checkpoint=next;if(!dirty)return;status('已保存本机 · 等待同步');clearTimeout(timer);timer=setTimeout(()=>sync(false),urgent?Math.max(0,5000-(Date.now()-lastWrite)):8000);}
 async function sync(force=false){clearTimeout(timer);if(!dirty||saving||!latest)return;if(!force&&Date.now()-lastWrite<5000){timer=setTimeout(()=>sync(),5000);return;}saving=true;const snapshot=structuredClone(latest);status('正在同步到 GitHub…');try{let result;try{result=await request('/state',{method:'PUT',body:JSON.stringify({state:snapshot,revision})});}catch(e){if(e.status!==409)throw e;revision=e.record.revision;const combined=replaceRequested?structuredClone(latest):merge(latest,e.record.state);latest=combined;window.GardenApp?.acceptCloudData(combined);result=await request('/state',{method:'PUT',body:JSON.stringify({state:combined,revision})});Object.assign(snapshot,combined);}revision=result.revision;lastSaved=JSON.stringify(snapshot);lastWrite=Date.now();replaceRequested=false;localStorage.removeItem(LOCAL+':replace:'+username);dirty=JSON.stringify(latest)!==lastSaved;localStorage.setItem(pendingKey(),String(dirty));status(dirty?'已保存本机 · 新进度待同步':'已同步到 GitHub · '+new Date(result.updatedAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'}),dirty?'pending':'saved');}catch(e){status(e.status===401?'登录已过期，请退出后重新输入账号名。':'云端暂时不可用 · 本机记录已保留','offline');dirty=true;localStorage.setItem(pendingKey(),'true');}finally{saving=false;if(dirty)timer=setTimeout(()=>sync(),15000);}}
 async function boot(record){username=record.username;token=record.token;revision=record.revision;sessionStorage.setItem('lixia-cloud-session',JSON.stringify({username,token}));replaceRequested=localStorage.getItem(LOCAL+':replace:'+username)==='true';let initial=record.state;const own=localStorage.getItem(cacheKey()),pending=localStorage.getItem(pendingKey())==='true';if(own&&pending)try{initial=replaceRequested?JSON.parse(own):merge(JSON.parse(own),initial);}catch{}
  if(!own&&!replaceRequested&&(location.hostname==='127.0.0.1'||location.hostname==='localhost')&&username==='lixia'){try{const legacy=JSON.parse(localStorage.getItem(LOCAL)||'null');if(legacy?.version===1)initial=merge(legacy,initial);}catch{}}
  if(initial)localStorage.setItem(cacheKey(),JSON.stringify(initial));window.AccountSession={username,storageKey:cacheKey(),apiBase:config.apiBase,observe,sync,merge,get token(){return token;}};
  document.getElementById('account-gate').remove();document.body.classList.remove('account-gated');const bar=document.createElement('div');bar.className='account-bar';bar.innerHTML='<strong id="account-name"></strong><span id="cloud-status" role="status"></span><button id="cloud-sync" class="text-button">立即同步</button><button id="account-logout" class="text-button">退出账号</button>';document.getElementById('main').prepend(bar);document.getElementById('account-name').textContent=username+' · V1.0';document.getElementById('cloud-sync').addEventListener('click',()=>sync(true));document.getElementById('account-logout').addEventListener('click',async()=>{window.GardenApp?.pause(false);await sync(true);sessionStorage.removeItem('lixia-cloud-session');location.reload();});
  for(const placeholder of document.querySelectorAll('script[data-app-src]')){await new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=placeholder.dataset.appSrc;s.onload=resolve;s.onerror=reject;document.body.append(s);});}started=true;latest=structuredClone(GardenApp.data);lastSaved=record.state?JSON.stringify(record.state):'';status(record.updatedAt?'已读取 GitHub 记录':'新账号记录已准备好',record.updatedAt?'saved':'pending');observe(latest);setInterval(()=>{if(dirty)sync();},30000);window.addEventListener('online',()=>sync());document.addEventListener('visibilitychange',()=>{if(document.hidden)sync();});window.addEventListener('pagehide',()=>{if(dirty)localStorage.setItem(pendingKey(),'true');});
 }
 async function main(){document.body.classList.add('account-gated');const gate=document.createElement('section');gate.id='account-gate';gate.innerHTML='<div class="login-art">✿</div><p class="eyebrow">立夏的打字小花园 · V1.0</p><h1>准备好，开始长本领。</h1><p>输入你的账号名，接着上次的进度练习。</p><form id="account-form"><label for="account-input">账号名</label><input id="account-input" autocomplete="username" maxlength="32" placeholder="请输入账号名" required><button class="primary-button">进入我的小花园</button></form><p id="account-error" role="status"></p><small>这是账号名识别入口，不使用密码。</small>';document.body.append(gate);document.getElementById('account-input').focus();try{const r=await fetch(new URL('cloud-config.json',base));config=await r.json();if(!config.apiBase.startsWith('https://'))throw Error('云端配置无效。');}catch{document.getElementById('account-error').textContent='云端配置未加载，请刷新页面。';return;}
  document.getElementById('account-form').addEventListener('submit',async ev=>{ev.preventDefault();const button=ev.target.querySelector('button');button.disabled=true;document.getElementById('account-error').textContent='正在读取你的 GitHub 记录…';try{const name=document.getElementById('account-input').value.trim();const record=await request('/session',{method:'POST',body:JSON.stringify({username:name})});await boot(record);}catch(e){const error=document.getElementById('account-error');if(error)error.textContent=e.message;}finally{button.disabled=false;}});
  try{const saved=JSON.parse(sessionStorage.getItem('lixia-cloud-session')||'null');if(saved){token=saved.token;const record=await request('/state');await boot({...record,username:saved.username,token});}}catch{sessionStorage.removeItem('lixia-cloud-session');token=null;}
 }
 main().catch(()=>{const e=document.getElementById('account-error');if(e)e.textContent='页面加载失败，请刷新后重试。';});
})();
