(() => {
 'use strict';const A=window.GardenApp,E=window.GardenEffects,$=id=>document.getElementById(id),data=()=>A.data,esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 let bubbleTimer,countdownTimer,growthType='correct',explanation=null,exam=null,game=null;
 function correct(key,physicalCode){const c=A.physicalChar(key);data().growth.correct[c]=(data().growth.correct[c]||0)+1;const code=physicalCode||(/^[a-z]$/.test(c)?'Key'+c.toUpperCase():/^\d$/.test(c)?'Digit'+c:c===' '?'Space':K.find(k=>k.label.toLowerCase()===c)?.code);if(code)data().growth.codes[code]=(data().growth.codes[code]||0)+1;A.save();}
 function heard(h){if(!/^[a-z0-9]$/.test(h.char))return;data().growth[h.mode][h.char]=(data().growth[h.mode][h.char]||0)+1;A.save();if(A.currentView==='growth')renderGrowth();}
 function showPinyin(h){const s=h.syllable;if(!s)return;clearTimeout(bubbleTimer);const needle=h.char==='v'?'ü':h.char;$('pinyin-bubble').innerHTML=`<span class="syllable">${s.parts.map(p=>`<b class="${p.raw===needle?'pressed-letter':''}">${p.text}</b>`).join('')}</span><span class="phonetic">[ ${esc(s.ipa)} ] · ${window.PinyinBank.names[s.tone]}</span>${h.char==='v'?'<small>V 键表示 ü</small>':''}`;$('pinyin-bubble').hidden=false;bubbleTimer=setTimeout(()=>$('pinyin-bubble').hidden=true,1000);}
 function renderProgress(){const d=data(),n=Object.keys(d.completions).length,passed=type=>d.exams.some(r=>r.type===type&&r.passed),units=n+['chinese','english','knowledge'].filter(passed).length,p=Math.round(units/28*100);$('journey-label').textContent=units===28?'毕业啦！继续练习，让本领更熟练。':`已完成 ${units} / 28 个目标 · 还差 ${28-units} 个`;$('journey-fill').style.width=p+'%';$('journey-track').setAttribute('aria-valuenow',p);$('journey-steps').innerHTML=[['基础键位',`${n} / 25 关`,n===25],['中文输入','50 个汉字',passed('chinese')],['英文输入','50 个单词',passed('english')],['键位知识','20 道题',passed('knowledge')]].map(([name,label,done])=>`<span class="${done?'done':''}"><i>${done?'✓':'○'}</i>${name}<small>${label}</small></span>`).join('');}
 function completed(result){cancelCountdown();const next=result.lesson.id==='review'?A.lessons.find(l=>!data().completions[l.id])||A.lessons.at(-1):A.lessons[result.index+1];$('next-lesson-name').textContent=next?'下一关已选好：'+next.title:'所有基础关卡完成啦，去考试检验本领吧！';$('next-countdown-text').textContent=next?'按回车，进入下一关':'按回车，查看小红花';$('next-button').focus();if(data().settings.autoNext&&next){let left=5;$('next-cancel').hidden=false;$('next-countdown-text').textContent=`${left} 秒后进入下一关 · 回车立即开始`;countdownTimer=setInterval(()=>{if(document.hidden||!$('result-dialog').open||A.currentView!=='practice'){cancelCountdown();return;}left--;if(left<=0){cancelCountdown();$('next-button').click();}else $('next-countdown-text').textContent=`${left} 秒后进入下一关 · 回车立即开始`;},1000);}}
 function cancelCountdown(){clearInterval(countdownTimer);countdownTimer=null;$('next-cancel').hidden=true;$('next-countdown-text').textContent='按回车，进入已选好的下一关';}
 $('next-cancel').addEventListener('click',cancelCountdown);$('result-dialog').addEventListener('close',cancelCountdown);$('result-dialog').addEventListener('keydown',ev=>{if(ev.key==='Enter'&&!ev.repeat){ev.preventDefault();cancelCountdown();$('next-button').click();}});
 function syncSettings(){$('auto-next-checkbox').checked=data().settings.autoNext;$('exam-minutes').value=data().settings.examMinutes;renderProgress();}
 $('auto-next-checkbox').addEventListener('change',ev=>{data().settings.autoNext=ev.target.checked;A.save();});$('exam-minutes').addEventListener('change',ev=>{data().settings.examMinutes=Number(ev.target.value);A.save();});
 function renderGrowth(){const values=data().growth[growthType];$('growth-total').textContent=`累计 ${Object.values(values).reduce((s,n)=>s+n,0)} 次${{correct:'正确按键',pinyin:'完整拼音听音',english:'完整英文听音'}[growthType]}`;const keys=growthType==='correct'?K:[...'abcdefghijklmnopqrstuvwxyz0123456789'].map(char=>({code:char,label:char.toUpperCase()}));$('heatmap').innerHTML=keys.map(key=>{const n=(growthType==='correct'?data().growth.codes[key.code]:values[key.code])||0;const label=key.code.startsWith('Numpad')?'小键盘 '+key.label:key.label;return `<button class="heat-key" style="--level:${Math.min(1,Math.log(1+n)/Math.log(101))}" title="${esc(label)}：${n} 次" aria-label="${esc(label)}，${n} 次"><strong class="${label.length>2?'utility-heat':''}">${esc(label)}</strong><small>${n} 次</small></button>`;}).join('');$('heatmap').querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>A.toast(b.getAttribute('aria-label'))));}
 $('growth-tabs').querySelectorAll('button').forEach(b=>b.addEventListener('click',()=>{growthType=b.dataset.growth;$('growth-tabs').querySelectorAll('button').forEach(n=>n.classList.toggle('active',n===b));renderGrowth();}));
 const K=[];function k(code,label,description,size=1,upper=''){const o={code,label,description,size,upper};K.push(o);return o;}
 const utility={Escape:['Esc · 退出键','想关掉一个小窗口或取消刚才的操作，可以试试它。在小花园里，Esc 可以暂停。'],Tab:['Tab · 制表键','写文章时，它能让光标向前空出一段。在网页上，按它可以找到下一个按钮。'],CapsLock:['Caps Lock · 大写锁定','打开以后，英文字母会一直变成大写。再按一下就关掉。输入密码时要看看它有没有亮。'],Backspace:['Backspace · 退格键','光标左边的字写错了，按一下就删掉左边一个字。'],Enter:['Enter · 回车键','写文章时用来换到下一行。填完答案时，常用它来确认。'],ShiftLeft:['Shift · 大写辅助键','按住它再按字母，可以写出大写字母。按住它再按数字，能打出键帽上方的符号。'],ShiftRight:['Shift · 大写辅助键','它和左边的 Shift 本领一样。用另一只手的小指帮忙，大写和符号就容易打了。'],ControlLeft:['Ctrl · 控制键','它是快捷键的小帮手。比如按住 Ctrl 再按 C 可以复制，Ctrl 加 V 可以粘贴。'],ControlRight:['Ctrl · 控制键','和左边的 Ctrl 一样，配合其他键使用。'],AltLeft:['Alt · 组合辅助键','它常和别的键一起用。按住 Alt 再按 Tab，可以在已经打开的窗口之间切换。'],AltRight:['Alt · 组合辅助键','配合其他键使用，具体效果由正在使用的软件决定。'],MetaLeft:['Win · Windows 键','键帽上像小窗户的图案。按一下，通常会打开开始菜单。按住它加空格可以切换输入法。'],Fn:['Fn · 功能辅助键','按住 Fn 再按带小图案的键，可能可以调音量、亮度。具体组合要看这台电脑的设置。浏览器通常读不到 Fn，请点击这里学习。'],ContextMenu:['专用键 · 电脑的小助手','照片上这个键带有专用图标。它的功能由电脑厂商和软件决定，可能打开菜单或电脑助手。'],Insert:['Insert · 插入键','写字时有些软件用它切换插入和覆盖。初学时通常不用按它。'],Delete:['Delete · 删除键','写文章时，它常常删掉光标右边的字。先看清楚要删什么再按。'],Home:['Home · 行首键','写文章时，常把光标送到这一行的开头。Home 的意思是家。'],End:['End · 行尾键','写文章时，常把光标送到这一行的末尾。End 的意思是结束。'],PageUp:['Page Up · 向上翻页','看长文章时，帮助你向上翻一页。Page 是页面，Up 是向上。'],PageDown:['Page Down · 向下翻页','帮助你向下翻一页。Down 的意思是向下。'],ArrowLeft:['← · 左方向键','把光标或选中的东西往左移动一步。'],ArrowRight:['→ · 右方向键','把光标或选中的东西往右移动一步。'],ArrowUp:['↑ · 上方向键','把光标或选中的东西往上移动。'],ArrowDown:['↓ · 下方向键','把光标或选中的东西往下移动。'],Space:['Space · 空格键','单词之间要留一个小空位，就用拇指按它。中文输入法里，它还常用来选择第一个汉字。'],NumLock:['Num Lock · 数字锁定','右边小键盘的开关。打开时按出数字，关闭时有些数字键变成方向或翻页。'],NumpadEnter:['Enter · 小键盘回车','它和主键盘的回车本领一样，右手小指可以按到它。']};
 function u(code,label,size=1){const [title,desc]=utility[code]||[label,'这是电脑的功能键。'];return k(code,label,`${title}。${desc}`,size);}
 const punctuation={'`':['反引号','~','波浪号'],'-':['减号','_','下划线'],'=':['等号','+','加号'],'[':['左方括号','{','左大括号'],']':['右方括号','}','右大括号'],'\\':['反斜杠','|','竖线'],';':['分号',':','冒号'],"'":['单引号','"','双引号'],',':['逗号','<','小于号'],'.':['句号','>','大于号'],'/':['斜杠','?','问号']};
 function ch(char,code,upper='',size=1){let desc;if(/[a-z]/.test(char))desc=`${char.toUpperCase()} 是英文字母键。直接按通常输入小写 ${char}；按住 Shift 可以输入大写 ${char.toUpperCase()}。${char==='f'?'左手食指的家，摸一摸小凸起。':char==='j'?'右手食指的家，摸一摸小凸起。':`练习时用${{LP:'左手小指',LR:'左手无名指',LM:'左手中指',LI:'左手食指',RI:'右手食指',RM:'右手中指',RR:'右手无名指',RP:'右手小指'}[A.fingerFor(char,false)]}按它，再回到中间一排。`}`;else if(/\d/.test(char))desc=`数字 ${char}。直接按可以写这个数字，按住 Shift 再按，可以写出上方的 ${upper} 符号。`;else{const p=punctuation[char];desc=`${p[0]}键。直接按，写出 ${char}；按住 Shift 再按，写出${p[2]} ${p[1]}。这是英文半角符号，中文输入法里显示可能不同。`;}return k(code,char.toUpperCase(),desc,size,upper);}
 const rows=[ [u('Escape','Esc'),...Array.from({length:12},(_,i)=>k('F'+(i+1),'F'+(i+1),`F${i+1} 是功能键。不同软件会给它安排不同任务。${i===0?'很多软件用 F1 打开帮助。':i===4?'浏览器里 F5 通常刷新页面。':''}照片上的小图案表示声音、屏幕等本领，有时要按住 Fn 配合。`)),u('Insert','Insert'),u('Home','Home'),u('End','End'),u('Delete','Delete')],
 [ch('`','Backquote','~'),...[...'1234567890'].map((c,i)=>ch(c,'Digit'+c,'!@#$%^&*()'[i])),ch('-','Minus','_'),ch('=','Equal','+'),u('Backspace','Backspace',2)],
 [u('Tab','Tab',1.5),...[...'qwertyuiop'].map(c=>ch(c,'Key'+c.toUpperCase())),ch('[','BracketLeft','{'),ch(']','BracketRight','}'),ch('\\','Backslash','|',1.5)],
 [u('CapsLock','Caps Lock',1.8),...[...'asdfghjkl'].map(c=>ch(c,'Key'+c.toUpperCase())),ch(';','Semicolon',':'),ch("'",'Quote','"'),u('Enter','Enter',2.2)],
 [u('ShiftLeft','Shift',2.2),...[...'zxcvbnm'].map(c=>ch(c,'Key'+c.toUpperCase())),ch(',','Comma','<'),ch('.','Period','>'),ch('/','Slash','?'),u('ShiftRight','Shift',2.8)],
 [u('ControlLeft','Ctrl',1.2),u('Fn','Fn'),u('MetaLeft','Win'),u('AltLeft','Alt'),u('Space','Space · 空格',5.5),u('AltRight','Alt'),u('ContextMenu','专用键'),u('PageUp','Pg Up'),u('ArrowUp','↑'),u('PageDown','Pg Dn')],
 [u('ArrowLeft','←'),u('ArrowDown','↓'),u('ArrowRight','→')]
 ];
 const numRows=[[u('NumLock','Num'),k('NumpadDivide','/','小键盘除号。算除法时可以用它，右手中指按。'),k('NumpadMultiply','*','小键盘乘号。计算时，星号常表示乘法，右手无名指按。'),k('NumpadSubtract','-','小键盘减号，右手小指按。')],[7,8,9].map(n=>k('Numpad'+n,String(n),`小键盘数字 ${n}。请先打开 Num Lock。用${n===7?'右食指':n===8?'右中指':'右无名指'}轻轻按，按完回到四、五、六。`)),[4,5,6].map(n=>k('Numpad'+n,String(n),`小键盘数字 ${n}。${n===5?'右中指的家，键帽上有小凸起。':n===4?'右食指的家。':'右无名指的家。'}先打开 Num Lock，再按数字。`)),[1,2,3].map(n=>k('Numpad'+n,String(n),`小键盘数字 ${n}。用${n===1?'右食指':n===2?'右中指':'右无名指'}轻按，按完回家。`)),[k('Numpad0','0','小键盘数字零。右手拇指按，先打开 Num Lock。',2),k('NumpadDecimal','.','小键盘小数点。例如三点五写成 3.5。右手无名指按。')]];
 const plus=k('NumpadAdd','+','小键盘加号。计算加法时用它，右手小指按。'),numEnter=u('NumpadEnter','Enter');
 function keyHTML(o){return `<button class="teach-key${['KeyF','KeyJ','Numpad5'].includes(o.code)?' anchor-key':''}" data-teach="${o.code}" style="--size:${o.size}" aria-label="${esc(o.label)}，点击听讲解">${o.upper?`<small>${esc(o.upper)}</small>`:''}<span>${esc(o.label)}</span></button>`;}
 for(const key of window.LaptopLayout.keys){const old=K.find(o=>o.code===key.code);if(!old){const desc=key.code==='LaunchApp2'?'计算器快捷键。按它可能打开电脑的计算器，具体效果由电脑设置决定。':key.code==='NumpadBackspace'?'小键盘上方的退格键，用来删掉光标左边的字。部分电脑按住 Fn 使用月亮图标的睡眠功能。':'小键盘上方的括号键，用来输入括号。它与字母右边的方括号位置不同。';K.push({...key,description:desc});}}
 $('teaching-keyboard').classList.add('laptop-board');$('teaching-keyboard').innerHTML=window.LaptopLayout.html(true);
 function explain(code,play=true){const o=K.find(k=>k.code===code);if(!o)return;explanation=o;document.querySelectorAll('.teach-key.lit').forEach(el=>el.classList.remove('lit'));document.querySelector(`[data-teach="${code==='F12'?'Insert':code}"]`)?.classList.add('lit');$('explain-label').textContent=o.label;$('explain-title').textContent=utility[code]?.[0]||o.label+' · '+(code.startsWith('Key')?'字母键':code.startsWith('Numpad')?'小键盘':'键盘小伙伴');$('explain-text').textContent=o.description;if(play){E.unlock();E.clickSound();void E.teachKey(code,o.description);}if(code.startsWith('Key')){const c=code.slice(3).toLowerCase();E.pressFinger(A.fingerFor(c,false),c);} }
 $('teaching-keyboard').addEventListener('click',ev=>{const b=ev.target.closest('[data-teach]');if(b)explain(b.dataset.teach);});$('explain-speak').addEventListener('click',()=>{E.unlock();if(explanation)void E.teachKey(explanation.code,explanation.description,{force:true});});
 document.addEventListener('keydown',ev=>{if(A.currentView!=='teaching'||ev.repeat||ev.isComposing||ev.target.matches('input,select,textarea'))return;if((ev.ctrlKey||ev.altKey||ev.metaKey)&&!['Control','Alt','Meta'].includes(ev.key))return;if(!K.some(k=>k.code===ev.code))return;if(ev.key!=='Tab')ev.preventDefault();explain(ev.code);});
 $('teaching-fullscreen').addEventListener('click',async()=>{if(document.fullscreenElement){await document.exitFullscreen();return;}try{await $('teaching-view').requestFullscreen();}catch{ $('teaching-view').classList.toggle('large-teaching');} });
 const cnPairs='山:shān 水:shuǐ 日:rì 月:yuè 火:huǒ 木:mù 土:tǔ 人:rén 口:kǒu 手:shǒu 大:dà 小:xiǎo 上:shàng 下:xià 中:zhōng 天:tiān 地:dì 云:yún 雨:yǔ 风:fēng 花:huā 草:cǎo 树:shù 叶:yè 鸟:niǎo 鱼:yú 虫:chóng 马:mǎ 牛:niú 羊:yáng 猫:māo 狗:gǒu 书:shū 笔:bǐ 字:zì 学:xué 校:xiào 老:lǎo 师:shī 友:yǒu 好:hǎo 爱:ài 家:jiā 妈:mā 爸:bà 米:mǐ 饭:fàn 茶:chá 果:guǒ 春:chūn'.split(' ').map(s=>{const [text,meaning]=s.split(':');return {text,meaning};});
 const enPairs='cat:猫 dog:狗 sun:太阳 moon:月亮 star:星星 book:书 pen:钢笔 pencil:铅笔 school:学校 home:家 tree:树 flower:花 grass:草 bird:鸟 fish:鱼 water:水 milk:牛奶 rice:米饭 apple:苹果 pear:梨 banana:香蕉 orange:橙子 red:红色 blue:蓝色 green:绿色 yellow:黄色 white:白色 black:黑色 pink:粉色 happy:快乐的 good:好的 kind:友善的 big:大的 small:小的 hand:手 foot:脚 eye:眼睛 nose:鼻子 ear:耳朵 mouth:嘴 mother:妈妈 father:爸爸 sister:姐妹 brother:兄弟 friend:朋友 teacher:老师 hello:你好 thank:感谢 love:爱 play:玩'.split(' ').map(s=>{const [text,meaning]=s.split(':');return {text,meaning};});
 const questions=[
 ['哪两个键有小凸起，是食指的家？',['F 和 J','A 和 L','Q 和 P'],0],['写大写字母，可以按住哪个键再按字母？',['Tab','Shift','Delete'],1],['退格 Backspace 常常删掉哪边的字？',['光标左边','光标右边','整篇文章'],0],['英文单词之间通常按哪个键？',['Fn','Esc','Space 空格'],2],['键帽上方的问号怎么打？',['按住 Shift 再按 /','只按数字 1','按 Tab'],0],['小键盘数字 5 是哪根手指的家？',['右中指','左食指','右拇指'],0],['小键盘按不出数字，可以先看看哪个键？',['Caps Lock','Num Lock','Ctrl'],1],['中文输入法里选第一个候选字，常用哪个键？',['空格','F1','Alt'],0],['光标去到行尾，常用哪个键？',['Home','End','Fn'],1],['常见复制快捷键是什么？',['Ctrl + C','Shift + A','Alt + F'],0],
 ['按键时，手指应当自然弯曲，按完回到基本键位。',['对','错'],0],['打字一开始就必须非常快。',['对','错'],1],['Enter 写文章时可以换行。',['对','错'],0],['Caps Lock 打开后，英文字母通常变成大写。',['对','错'],0],['Delete 和 Backspace 在文章里总是删除同一侧的字。',['对','错'],1],['Fn 在所有电脑上都有完全一样的快捷键。',['对','错'],1],['小键盘的 / 常表示除法，* 常表示乘法。',['对','错'],0],['Page Down 的意思是向下翻页。',['对','错'],0],['空格键可以用拇指按。',['对','错'],0],['中文考试只输入英文字母拼音，也算输入了汉字。',['对','错'],1]
 ];
 const allKnowledge=K.map((key,i)=>{const choices=[key.label,K[(i+17)%K.length].label,K[(i+37)%K.length].label];return [key.description.replace(/^.+?[。]/,'')+' 这说的是哪个键？',choices,0];});
 function shuffle(list){const a=[...list];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]];}return a;}
 function beginExam(type){$('exam-resume')?.remove();if(exam?.running)finishExam('已结束上一次考试。');E.unlock();E.stopAudio();exam={type,items:shuffle(type==='chinese'?cnPairs:type==='english'?enPairs:[...shuffle([...questions.filter(q=>q[1].length===3),...allKnowledge]).slice(0,10),...questions.filter(q=>q[1].length===2)]),index:0,correct:0,wrong:0,elapsed:0,last:performance.now(),limit:(type==='knowledge'?5:data().settings.examMinutes)*60,running:true,paused:false,composing:false};$('exam-choice').hidden=true;$('exam-summary').hidden=true;$('exam-work').hidden=false;$('exam-kind').textContent={chinese:'中文输入考试',english:'英文单词考试',knowledge:'全键位知识考试'}[type];$('exam-form').hidden=type==='knowledge';$('exam-options').hidden=type!=='knowledge';renderExam();void E.speakText(type==='chinese'?'这次用中文拼音输入法，选出屏幕上的汉字。先切到中文输入，再点答案框。':type==='english'?'这次拼写英文单词。切到英文输入，写好一个单词后按空格或回车。':'认真读题，选一个你认为正确的答案。');if(type!=='knowledge')$('exam-input').focus();}
 function renderExam(){if(!exam)return;const item=exam.items[exam.index];if(!item){finishExam();return;}$('exam-count').textContent=`${exam.correct} / ${exam.items.length} ${exam.type==='knowledge'?'题答对':'已完成'}`;$('exam-time').textContent=formatTime(Math.ceil(exam.limit-exam.elapsed));$('exam-progress').style.width=(exam.index/exam.items.length*100)+'%';$('exam-feedback').textContent='';$('exam-input').value='';$('exam-input').disabled=false;
 if(exam.type==='knowledge'){$('exam-prompt').textContent=`第 ${exam.index+1} / 20 题：${item[0]}`;$('exam-help').textContent='选择一个答案；答完会告诉你正确答案。';$('exam-options').innerHTML=item[1].map((label,i)=>`<button data-answer="${i}" class="outline-button">${esc(label)}</button>`).join('');}else{$('exam-prompt').innerHTML=`<strong>${esc(item.text)}</strong><span>${esc(item.meaning)}</span>`;$('exam-help').textContent=exam.type==='chinese'?'用中文拼音输入法输入上面的汉字。选词后会自动检查。':'输入完整英文单词，再按空格或回车。';}}
 function submitTyped(){if(!exam?.running||exam.paused||exam.composing||exam.type==='knowledge')return;const value=$('exam-input').value.trim();if(!value)return;const target=exam.items[exam.index].text;if(value===target){for(const c of (exam.type==='english'?target:exam.items[exam.index].meaning.normalize('NFD').replace(/[\u0300-\u036f]/g,'')))correct(c);exam.correct++;exam.index++;$('exam-input').value='';E.clickSound();if(exam.index===50){finishExam();return;}renderExam();$('exam-input').focus();}else{exam.wrong++;$('exam-feedback').textContent=exam.type==='chinese'&&/^[a-z]+$/i.test(value)?'这里要输入真正的汉字，请切到中文拼音输入法，再选词。':'这次还没写对，看看上面的内容，再试一次。';$('exam-input').select();void E.speak('mistake-1',{throttle:5000});}}
 $('exam-choice').querySelectorAll('[data-exam]').forEach(b=>b.addEventListener('click',()=>beginExam(b.dataset.exam)));$('exam-form').addEventListener('submit',ev=>{ev.preventDefault();submitTyped();});$('exam-input').addEventListener('compositionstart',()=>{if(exam)exam.composing=true;});$('exam-input').addEventListener('compositionend',()=>{if(exam){exam.composing=false;queueMicrotask(()=>{if(exam?.type==='chinese')submitTyped();});}});$('exam-input').addEventListener('input',ev=>{if(exam?.type==='chinese'&&!exam.composing&&!ev.isComposing&&/[^\x00-\x7F]/.test($('exam-input').value))submitTyped();});
 $('exam-input').addEventListener('keydown',ev=>{if(!exam?.running||exam.paused||ev.isComposing||exam.composing||ev.keyCode===229)return;if(ev.repeat)return;if(ev.key===' '&&exam.type==='english'){ev.preventDefault();submitTyped();return;}if(ev.key.length===1&&/^[a-z0-9]$/i.test(ev.key)){E.clickSound();E.pronounce(ev.key,{mode:exam.type==='english'?'english':'pinyin'});E.pressFinger(A.fingerFor(ev.key,false),ev.key);}});
 for(const name of ['paste','drop'])$('exam-input').addEventListener(name,ev=>{ev.preventDefault();$('exam-feedback').textContent='考试时请自己敲键盘，粘贴的内容不计入成绩。';});$('exam-input').addEventListener('beforeinput',ev=>{if(['insertFromPaste','insertFromDrop'].includes(ev.inputType))ev.preventDefault();});
 $('exam-options').addEventListener('click',ev=>{const b=ev.target.closest('[data-answer]');if(!b||!exam?.running||exam.paused)return;const item=exam.items[exam.index],ok=Number(b.dataset.answer)===item[2];if(ok)exam.correct++;else exam.wrong++;exam.index++;$('exam-options').querySelectorAll('button').forEach(n=>n.disabled=true);$('exam-feedback').textContent=ok?'答对啦！':'正确答案是：'+item[1][item[2]]+'。记住这个小本领。';void E.speakText(ok?'答对啦！':'正确答案是，'+item[1][item[2]]+'。没关系，记住它再试。');const btn=document.createElement('button');btn.className='primary-button';btn.textContent=exam.index===20?'查看成绩':'下一题';btn.addEventListener('click',()=>{if(!exam?.running)return;renderExam();});$('exam-options').append(btn);});
 function formatTime(sec){return Math.floor(Math.max(0,sec)/60)+':'+String(Math.floor(Math.max(0,sec)%60)).padStart(2,'0');}
 function finishExam(reason=''){if(!exam?.running)return;exam.running=false;$('exam-resume')?.remove();const accuracy=exam.correct/(exam.correct+exam.wrong||1),passed=exam.type==='knowledge'?exam.correct>=17:exam.correct===50&&accuracy>=.9&&exam.elapsed<=exam.limit;const record={type:exam.type,date:new Date().toISOString(),correct:exam.correct,wrong:exam.wrong,seconds:Math.ceil(exam.elapsed),passed};data().exams.push(record);data().exams=data().exams.slice(-100);A.save();$('exam-work').hidden=true;$('exam-choice').hidden=false;$('exam-summary').hidden=false;$('exam-summary').innerHTML=`<h2>${passed?'挑战通过啦！':'这次的认真，已经记住。'}</h2><p>${esc(reason)} 完成 ${exam.correct} / ${exam.items.length}，错误 ${exam.wrong} 次，用时 ${formatTime(exam.elapsed)}。</p><p>${passed?'毕业路线前进一步！':'再练熟一些，下次还可以挑战。'}</p><button class="primary-button" id="exam-retry">再试这项挑战</button>`;$('exam-retry').addEventListener('click',()=>beginExam(record.type));renderExamHistory();renderProgress();void E.speakText(passed?'太棒了，你通过了这个挑战！你的认真又让你前进了一步。':'这次的认真已经记住。先练一练，准备好后再来挑战。');}
 $('exam-stop').addEventListener('click',()=>finishExam('你主动结束了考试。'));
 function renderExamHistory(){$('exam-history').innerHTML=data().exams.length?data().exams.slice(-10).reverse().map(r=>`<div class="history-row"><strong>${{chinese:'中文 50 字',english:'英文 50 词',knowledge:'键位知识'}[r.type]}</strong><span>${r.correct} / ${r.type==='knowledge'?20:50} · ${r.passed?'通过':'再练练'}</span><small>${esc(r.date.slice(0,10))} · ${formatTime(r.seconds)}</small></div>`).join(''):'<p class="empty-note">准备好了再开始，第一次成绩会出现在这里。</p>';}
 function beginGame(){E.unlock();E.stopAudio();if(game?.running)endGame(false);game={running:true,paused:false,score:0,collected:0,misses:0,combo:0,elapsed:0,last:performance.now(),spawn:0,stars:[],level:$('game-level').value,name:$('player-name').value.trim().slice(0,12)||'立夏'};data().settings.gameLevel=game.level;A.save();$('star-arena').querySelectorAll('.falling-star,.star-burst,.star-particle,.combo-flash').forEach(e=>e.remove());$('game-overlay').hidden=true;$('game-start').disabled=true;$('game-level').disabled=true;$('player-name').disabled=true;$('game-pause').disabled=false;$('game-pause').textContent='暂停';$('star-arena').focus({preventScroll:true});$('game-feedback').textContent='看看最靠近地面的星星，按准它！';spawnStar();updateGameStats();}
 function spawnStar(){if(!game)return;const pool=game.level==='letters'?'abcdefghijklmnopqrstuvwxyz':game.level==='mixed'?'abcdefghijklmnopqrstuvwxyz0123456789':'abcdefghijklmnopqrstuvwxyz0123456789!?@#$%+-=,./;';const c=pool[Math.floor(Math.random()*pool.length)],el=document.createElement('div');el.className='falling-star';el.innerHTML=`<span>${esc(c)}</span>`;el.setAttribute('aria-label','星星 '+c);const x=.08+Math.random()*.84;const star={char:c,x,y:-60,speed:game.level==='letters'?35:game.level==='mixed'?47:56,el};game.stars.push(star);$('star-arena').append(el);el.style.left=(x*100)+'%';}
 function updateGameStats(){if(!game)return;$('game-score').textContent=game.score+' 分';$('game-lives').textContent='还能漏 '+Math.max(0,5-game.misses)+' 颗';$('game-time').textContent=Math.ceil(Math.max(0,60-game.elapsed))+' 秒';}
 function pauseGame(){if(!game?.running)return;game.paused=true;$('game-pause').textContent='继续';$('game-overlay').hidden=false;$('game-overlay').innerHTML='<strong>星星正在等你。</strong><span>点击“继续”，星星和时间一起接着走。</span>';}
 function resumeGame(){if(!game?.running)return;game.paused=false;game.last=performance.now();$('game-overlay').hidden=true;$('game-pause').textContent='暂停';$('star-arena').focus({preventScroll:true});}
 function endGame(record=true){if(!game?.running)return;game.running=false;if(record){data().rankings.push({name:game.name,score:game.score,date:new Date().toISOString(),level:game.level,collected:game.collected});data().rankings=data().rankings.slice(-100);A.save();}$('game-overlay').hidden=false;$('game-overlay').innerHTML=`<strong>收集了 ${game.collected} 颗星 · ${game.score} 分</strong><span>真认真！再练一场，也可以挑战另一种星空。</span>`;$('game-start').disabled=false;$('game-level').disabled=false;$('player-name').disabled=false;$('game-pause').disabled=true;$('game-feedback').textContent='成绩已保存在当前账号，下面可以看到这场成绩。';renderRanking();void E.speakText('你收集了'+game.collected+'颗星星，做得很好！小手放松一下，再来挑战吧。');}
 $('game-start').addEventListener('click',beginGame);$('game-pause').addEventListener('click',()=>game?.paused?resumeGame():pauseGame());$('star-arena').addEventListener('keydown',ev=>{if(!game?.running||game.paused||ev.repeat||ev.ctrlKey||ev.metaKey||ev.altKey||ev.isComposing)return;if(ev.key==='Escape'){ev.preventDefault();pauseGame();return;}if(ev.key.length!==1)return;ev.preventDefault();E.clickSound();E.pronounce(ev.key);E.pressFinger(A.fingerFor(ev.key,false),ev.key);const matches=game.stars.filter(s=>s.char===ev.key).sort((a,b)=>b.y-a.y);if(matches.length){const s=matches[0];game.stars.splice(game.stars.indexOf(s),1);window.GardenV4?.burst(s,game.combo+1);s.el.classList.add('star-burst');s.el.style.top=s.y+'px';setTimeout(()=>s.el.remove(),400);game.combo++;game.collected++;game.score+=10+Math.min(5,game.combo);correct(ev.key,ev.code);$('game-feedback').textContent='收到了！已经收下 '+game.collected+' 颗星。';}else{game.combo=0;$('game-feedback').textContent='这次没有对应的星星，认准上面的键再试试。';}updateGameStats();});
 $('game-level').addEventListener('change',()=>{data().settings.gameLevel=$('game-level').value;A.save();renderRanking();});
 function renderRanking(){const level=$('game-level').value,rows=data().rankings.filter(r=>r.level===level).sort((a,b)=>b.score-a.score||b.collected-a.collected).slice(0,20);$('ranking-list').innerHTML=rows.length?`<table class="ranking-table"><thead><tr><th>排名</th><th>名字</th><th>分数</th><th>星星</th><th>日期</th></tr></thead><tbody>${rows.map((r,i)=>`<tr><td>${i+1}</td><td>${esc(r.name)}</td><td>${r.score}</td><td>${r.collected}</td><td>${esc(r.date.slice(0,10))}</td></tr>`).join('')}</tbody></table>`:'<p class="empty-note">这一片星空还没有成绩，第一次排名等着你。</p>';}
 function frame(now){requestAnimationFrame(frame);if(game?.running){const dt=Math.min(.1,(now-game.last)/1000);game.last=now;if(!game.paused&&A.currentView==='game'){game.elapsed+=dt;game.spawn+=dt;const spawnEvery=Math.max(.9,(game.level==='letters'?2:1.6)-game.elapsed*.008);if(game.spawn>=spawnEvery&&game.stars.length<12){game.spawn=0;spawnStar();}const floor=$('star-arena').clientHeight-60;for(const s of [...game.stars]){s.y+=s.speed*dt;s.el.style.top=s.y+'px';if(s.y>=floor){s.el.remove();game.stars.splice(game.stars.indexOf(s),1);game.misses++;game.combo=0;}}updateGameStats();if(game.misses>=5||game.elapsed>=60)endGame();}}
 if(exam?.running){const dt=Math.min(.1,(now-exam.last)/1000);exam.last=now;if(!exam.paused&&A.currentView==='exam'){exam.elapsed+=dt;$('exam-time').textContent=formatTime(Math.ceil(exam.limit-exam.elapsed));if(exam.elapsed>=exam.limit)finishExam('时间到啦。');}}}
 requestAnimationFrame(frame);
 function suspend(){cancelCountdown();if(game?.running)pauseGame();if(exam?.running&&!exam.paused){exam.paused=true;$('exam-input').disabled=true;$('exam-feedback').textContent='考试已暂停，点击下方按钮继续。';let b=$('exam-resume');if(!b){b=document.createElement('button');b.id='exam-resume';b.className='primary-button';b.textContent='继续考试';b.addEventListener('click',()=>{if(!exam?.running)return;exam.paused=false;exam.last=performance.now();$('exam-input').disabled=false;b.remove();$('exam-feedback').textContent='继续认真写吧。';if(exam.type!=='knowledge')$('exam-input').focus();});$('exam-work').append(b);}}}
 window.addEventListener('garden-view',ev=>{if(ev.detail!=='practice')cancelCountdown();if(ev.detail!=='game'&&game?.running)pauseGame();if(ev.detail!=='exam'&&exam?.running)suspend();if(ev.detail==='growth')renderGrowth();if(ev.detail==='exam')renderExamHistory();if(ev.detail==='game')renderRanking();if(ev.detail==='teaching'&&!explanation)explain('KeyF',false);renderProgress();});window.addEventListener('blur',suspend);document.addEventListener('visibilitychange',()=>{if(document.hidden)suspend();});
 window.GardenPlus={correct,heard,showPinyin,renderProgress,completed,syncSettings,renderGrowth,beginExam,beginGame,get exam(){return exam;},get game(){return game;},keys:K,explain};
 $('game-level').value=data().settings.gameLevel;syncSettings();renderGrowth();renderExamHistory();renderRanking();
 $('mimo-status').textContent='V1.0：键位讲解和汉字读音已录制在网页中；新的动态提醒使用云端 MiMo 女声。';
})();
