(() => {
 const A=GardenApp,E=GardenEffects,$=id=>document.getElementById(id);let spelling=null,nextTimer,studyPlayed=false;
 const items='山:shān:shan 水:shuǐ:shui 猫:māo:mao 狗:gǒu:gou 花:huā:hua 家:jiā:jia 风:fēng:feng 雨:yǔ:yu 月:yuè:yue 云:yún:yun 书:shū:shu 天:tiān:tian 好:hǎo:hao 学:xué:xue 习:xí:xi 树:shù:shu 米:mǐ:mi 鱼:yú:yu 女:nǚ:nv 绿:lǜ:lv'.split(' ').map((s,i)=>{const [hanzi,pinyin,typed]=s.split(':');return {id:'word-'+i,hanzi,pinyin,typed};});
 function render(){if(!spelling)return;const word=items[spelling.index];$('spell-character').textContent=word.hanzi;$('spell-pinyin').textContent=word.pinyin;$('spell-letters').innerHTML=[...word.typed].map((c,i)=>`<span class="${i<spelling.pos?'typed':i===spelling.pos?'now':''}">${c}</span>`).join('');$('spell-progress').textContent=`${spelling.index+1} / ${items.length} · 已拼对 ${spelling.correct} 个`;$('spell-keyboard').innerHTML=LaptopLayout.html(false);const hints=A.data.settings.spellingHints!==false;$('spell-hints').textContent=hints?'隐藏键位提示':'显示键位提示';if(hints)for(const c of word.typed){const key=$('spell-keyboard').querySelector(`[data-code="Key${c.toUpperCase()}"]`);key?.classList.add('spelling-key');}if(hints)$('spell-keyboard').querySelector(`[data-code="Key${word.typed[spelling.pos]?.toUpperCase()}"]`)?.classList.add('current-key');}
 function question(){render();$('spell-feedback').textContent=items[spelling.index].typed.includes('v')?'ü 用 V 键输入，不用打声调。':'照着拼音，按英文字母；不用打声调。';void E.playStudy(items[spelling.index].id);$('spell-pad').focus({preventScroll:true});}
 function start(){clearTimeout(nextTimer);E.unlock();spelling={index:0,pos:0,correct:0,locked:false};$('spell-start').hidden=true;$('spell-work').hidden=false;question();}
 $('spell-start').addEventListener('click',start);$('spell-replay').addEventListener('click',()=>{if(spelling)void E.playStudy(items[spelling.index].id);});$('spell-hints').addEventListener('click',()=>{A.data.settings.spellingHints=A.data.settings.spellingHints===false;A.save();render();$('spell-pad').focus();});
 $('spell-pad').addEventListener('keydown',ev=>{if(!spelling||spelling.locked||A.currentView!=='spelling'||ev.ctrlKey||ev.altKey||ev.metaKey||ev.repeat)return;if(ev.isComposing||ev.key==='Process'||ev.keyCode===229){$('spell-feedback').textContent='请先切到英文输入，再敲拼音字母。';return;}if(ev.key.length!==1)return;ev.preventDefault();const word=items[spelling.index];E.clickSound();E.pressFinger(A.fingerFor(ev.key,false),ev.key);if(ev.key.toLowerCase()!==word.typed[spelling.pos]){$('spell-feedback').textContent='没关系，找准亮着的键，再试一次。';return;}GardenPlus.correct(ev.key,ev.code);spelling.pos++;render();if(spelling.pos!==word.typed.length)return;spelling.locked=true;spelling.correct++;spelling.advancePending=true;A.data.spelling.correct++;A.save();$('spell-feedback').textContent=`拼对了！${word.hanzi} · ${word.pinyin}，再听一次正确读音。`;void E.playStudy(word.id);nextTimer=setTimeout(()=>{if(A.currentView!=='spelling')return;spelling.advancePending=false;if(spelling.index===items.length-1){spelling.finished=true;A.data.spelling.sessions++;A.save();$('spell-feedback').textContent='20 个拼音都完成啦！你已经认真拼写了一整组。';$('spell-start').hidden=false;$('spell-start').textContent='再练一组';return;}spelling.index++;spelling.pos=0;spelling.locked=false;question();},1600);});
 window.addEventListener('garden-view',ev=>{if(ev.detail!=='spelling'){clearTimeout(nextTimer);E.stopAudio();}else if(spelling){if(spelling.advancePending){spelling.advancePending=false;if(spelling.index<items.length-1){spelling.index++;spelling.pos=0;spelling.locked=false;}else if(!spelling.finished){spelling.finished=true;A.data.spelling.sessions++;A.save();$('spell-start').hidden=false;$('spell-start').textContent='再练一组';}}render();}});
 const status=$('teaching-audio-ready');$('teaching-voice-checkbox').checked=A.data.settings.teachingVoice!==false;$('teaching-voice-checkbox').addEventListener('change',ev=>{A.data.settings.teachingVoice=ev.target.checked;A.save();if(!ev.target.checked)E.stopAudio();status.textContent=ev.target.checked?'按一个键，马上听讲解。':'教学讲解已关闭，勾选上方开关就能开启。';});E.teachingPromise=E.prepareTeaching().then(()=>{status.textContent=A.data.settings.teachingVoice!==false?'讲解语音已准备好，按一次键就能听。':'教学讲解已关闭，可以勾选上方开关。';}).catch(()=>{status.textContent='教学语音未加载完成，请重新打开页面。';throw Error('教学语音加载失败');});E.teachingPromise.catch(()=>{});
 const arena=$('star-arena'),canvas=document.createElement('canvas');canvas.className='cosmic-canvas';canvas.setAttribute('aria-hidden','true');arena.prepend(canvas);const ctx=canvas.getContext('2d'),dots=Array.from({length:95},()=>({x:Math.random(),y:Math.random(),r:Math.random()*1.4+.3,s:Math.random()*2}));
 function sky(t){requestAnimationFrame(sky);if(document.hidden||A.currentView!=='game')return;if(A.data.settings.animations===false||matchMedia('(prefers-reduced-motion: reduce)').matches)t=0;const w=arena.clientWidth,h=arena.clientHeight;if(canvas.width!==w||canvas.height!==h){canvas.width=w;canvas.height=h;}ctx.clearRect(0,0,w,h);for(const d of dots){ctx.globalAlpha=.4+Math.sin(t*.001+d.s*4)*.3;ctx.fillStyle='#d7f8ff';ctx.beginPath();ctx.arc(d.x*w,d.y*h,d.r,0,Math.PI*2);ctx.fill();}ctx.globalAlpha=1;}requestAnimationFrame(sky);
 function burst(star,combo){if(A.data.settings.animations===false||matchMedia('(prefers-reduced-motion: reduce)').matches)return;const layer=arena;for(let i=0;i<22;i++){const p=document.createElement('i'),angle=Math.PI*2*i/22;p.className='star-particle';p.style.left=star.x*100+'%';p.style.top=star.y+30+'px';p.style.setProperty('--dx',Math.cos(angle)*(55+Math.random()*40)+'px');p.style.setProperty('--dy',Math.sin(angle)*(55+Math.random()*40)+'px');layer.append(p);setTimeout(()=>p.remove(),650);}if(combo>=3){const flash=document.createElement('div');flash.className='combo-flash';flash.textContent='连续命中 × '+combo;layer.append(flash);setTimeout(()=>flash.remove(),800);}}
 window.GardenV4={items,get spelling(){return spelling;},start,burst};
})();
