const http=require('node:http'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),vm=require('node:vm');
const root=__dirname,port=8878,cacheDir=path.join(root,'.private','audio');fs.mkdirSync(cacheDir,{recursive:true});
const ctx={window:{}};vm.runInNewContext(fs.readFileSync(path.join(root,'pinyin-data.js'),'utf8'),ctx);const bank=ctx.window.PinyinBank.bank;
const oldManifest=JSON.parse(fs.readFileSync(path.join(root,'assets/audio/manifest.json'),'utf8'));
const publicFiles=new Set(['index.html','styles.css','v3.css','lessons.js','effects.js','app.js','expansion.js','hands3d.js','pinyin-data.js','laptop-layout.js','hands-photo.js','revision4.js','v4.css','account.js','account.css','cloud-config.json']);
const types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'text/javascript; charset=utf-8','.png':'image/png','.webp':'image/webp','.json':'application/json; charset=utf-8','.mp3':'audio/mpeg','.wav':'audio/wav'};
const inflight=new Map();let active=0;const queue=[];async function slot(){if(active>=4)await new Promise(r=>queue.push(r));active++;}function release(){active--;queue.shift()?.();}
function config(){try{return JSON.parse(fs.readFileSync(path.join(root,'.private/mimo.json'),'utf8'));}catch{return {baseURL:'https://mimo.ezlook.top/v1',apiKey:process.env.MIMO_API_KEY};}}
function audioSpec(body){const id=String(body.id||'');
 if(id.startsWith('syllable/')){const s=bank.find(s=>s.id===id.slice(9));if(!s)throw Error('未知拼音');return {text:s.example,style:`你是一位女性普通话拼音老师。只发出一个完整汉语拼音音节 ${s.display}，声调是第${s.tone}声。不是英文，不要说解释，不要读数字。准确地读这个音节一次。`,kind:'pinyin'};}
 if(id.startsWith('english/')){const ch=id.slice(8);if(!/^[a-z0-9]$/.test(ch))throw Error('未知字母');const letterNames=['ay','bee','see','dee','ee','eff','gee','aitch','eye','jay','kay','ell','em','en','oh','pee','cue','are','ess','tea','you','vee','double you','ex','why','zee'];const nums=['zero','one','two','three','four','five','six','seven','eight','nine'];return {text:/[a-z]/.test(ch)?letterNames[ch.charCodeAt(0)-97]:nums[Number(ch)],style:'A warm adult female American English teacher. Say only this English letter name or number once, clearly. No commentary.',kind:'english'};}
 if(id.startsWith('pinyin/')&&/^\d$/.test(id.slice(7)))return {text:'零一二三四五六七八九'[Number(id.slice(7))],style:'女性普通话教师，清楚读这个数字。',kind:'key'};
 if(oldManifest.clips[id])return {text:oldManifest.clips[id].text,style:'温柔清晰的成年女性普通话老师，给小学三年级小朋友讲话，语速稍慢，鼓励而不夸张。',kind:'guide'};
 if(id==='guide'&&typeof body.text==='string'&&body.text.length>0&&body.text.length<=600)return {text:body.text,style:'温柔清晰的成年女性普通话老师。小学三年级的小朋友正在学键盘，请说得自然，语速稍慢。',kind:'guide'};
 throw Error('未知语音');}
async function synthesize(spec){const c=config();if(!c.apiKey)throw Error('请配置 MiMo 密钥');const reference=path.join(root,'.private/mimo-reference.wav'),clone=spec.kind==='guide'&&spec.text.length>=80&&fs.existsSync(reference),model=clone?'mimo-v2.5-tts-voiceclone':'mimo-v2.5-tts';const voice=clone?'data:audio/wav;base64,'+fs.readFileSync(reference).toString('base64'):spec.kind==='english'?'Chloe':'茉莉';
 const hash=crypto.createHash('sha256').update(JSON.stringify({model,voice,...spec})).digest('hex'),file=path.join(cacheDir,hash+'.wav');
 if(fs.existsSync(file)&&fs.statSync(file).size>100)return hash;if(inflight.has(hash))return inflight.get(hash);
 const job=(async()=>{await slot();try{const response=await fetch(c.baseURL.replace(/\/$/,'')+'/chat/completions',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+c.apiKey},body:JSON.stringify({model,messages:[{role:'user',content:spec.style},{role:'assistant',content:spec.text}],audio:{format:'wav',voice}}),signal:AbortSignal.timeout(90000)});
 if(!response.ok)throw Error('MiMo 服务返回 '+response.status);const j=await response.json(),data=j.choices?.[0]?.message?.audio?.data;if(!data)throw Error('MiMo 没有返回音频');const audio=Buffer.from(data,'base64');if(audio.length<100)throw Error('MiMo 返回空音频');fs.writeFileSync(file+'.tmp',audio);fs.renameSync(file+'.tmp',file);return hash;}finally{release();inflight.delete(hash);}})();inflight.set(hash,job);return job;}
function json(res,status,data){res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store'});res.end(JSON.stringify(data));}
const server=http.createServer(async(req,res)=>{
 let pathname;try{pathname=decodeURIComponent(new URL(req.url,'http://127.0.0.1').pathname);}catch{res.writeHead(400);res.end();return;}
 res.setHeader('X-Lixia-Typing','garden-v4');res.setHeader('X-Content-Type-Options','nosniff');
 if(pathname==='/api/voice-status'&&req.method==='GET'){json(res,200,{provider:'MiMo',model:'mimo-v2.5-tts',configured:!!config().apiKey,cached:fs.readdirSync(cacheDir).filter(f=>f.endsWith('.wav')).length});return;}
 if(pathname==='/api/tts'&&req.method==='POST'){if(req.headers.host!==`127.0.0.1:${port}`||req.headers.origin&&req.headers.origin!==`http://127.0.0.1:${port}`){json(res,403,{error:'请从本机小花园访问'});return;}let body='';try{for await(const chunk of req){body+=chunk;if(Buffer.byteLength(body)>5000)throw Error('请求过长');}const payload=JSON.parse(body);if(/^study\/[a-z0-9-]+$/.test(payload.id||'')){const file=path.join(root,'assets',payload.id+'.wav');if(fs.existsSync(file)){json(res,200,{url:'/assets/'+payload.id+'.wav',provider:'MiMo',model:'mimo-v2.5-tts'});return;}}if(/^english\/[a-z]$/.test(payload.id||'')){const letterFile=path.join(root,'assets/mimo','english-'+payload.id.slice(8)+'.wav');if(fs.existsSync(letterFile)){json(res,200,{url:'/assets/mimo/english-'+payload.id.slice(8)+'.wav',provider:'MiMo',model:'mimo-v2.5-tts',text:payload.id.slice(8).toUpperCase()});return;}}if(/^syllable\/[a-zv]+-[1-4]$/.test(payload.id||'')){const syllableFile=path.join(root,'assets/mimo',payload.id.slice(9)+'.wav');if(fs.existsSync(syllableFile)){json(res,200,{url:'/assets/mimo/'+payload.id.slice(9)+'.wav',provider:'MiMo',model:'mimo-v2.5-tts',text:bank.find(s=>s.id===payload.id.slice(9))?.display});return;}}const spec=audioSpec(payload),hash=await synthesize(spec);json(res,200,{url:'/api/audio/'+hash+'.wav',provider:'MiMo',model:spec.kind==='guide'&&spec.text.length>=80&&fs.existsSync(path.join(root,'.private/mimo-reference.wav'))?'mimo-v2.5-tts-voiceclone':'mimo-v2.5-tts',text:spec.text});}catch(e){json(res,502,{error:e.message.startsWith('MiMo')?e.message:'语音暂时不可用，请检查本机服务或稍后重试'});}return;}
 if(!['GET','HEAD'].includes(req.method)){res.writeHead(405);res.end();return;}
 if(pathname==='/health'){res.writeHead(200,{'Content-Type':'text/plain','Cache-Control':'no-store'});res.end('lixia-typing-garden-v1');return;}if(pathname==='/favicon.ico'){res.writeHead(204);res.end();return;}
 const filename=pathname==='/'?'index.html':pathname.slice(1),audio=/^\/api\/audio\/([a-f0-9]{64})\.wav$/.exec(pathname);let absolute;
 if(audio)absolute=path.join(cacheDir,audio[1]+'.wav');else{const asset=/^assets\/(?:[a-zA-Z0-9-]+\.(?:png|webp)|mimo\/(?:[a-zv]+-[1-4]|english-[a-z])\.wav|release-voices\/(?:manifest\.json|[A-Za-z0-9-]+\.wav)|(?:teaching|study)\/(?:manifest\.json|[A-Za-z0-9-]+\.(?:wav|mp3))|mimo\/manifest\.json|vendor\/three\.(?:core|module)\.js|audio\/manifest\.json|audio\/(?:pinyin|english|keys|prompts)\/[a-zA-Z0-9-]+\.mp3)$/.test(filename);if(!publicFiles.has(filename)&&!asset){res.writeHead(404);res.end();return;}absolute=path.resolve(root,filename);if(!absolute.startsWith(root+path.sep)){res.writeHead(404);res.end();return;}}
 fs.stat(absolute,(err,stat)=>{if(err||!stat.isFile()){res.writeHead(404);res.end();return;}res.setHeader('Cache-Control',audio?'private, max-age=31536000':'no-store');res.writeHead(200,{'Content-Type':types[path.extname(absolute)]||'application/octet-stream','Content-Length':stat.size});if(req.method==='HEAD')res.end();else fs.createReadStream(absolute).pipe(res);});
});
server.on('error',err=>{process.stderr.write('Typing garden could not start: '+err.code+'\n');process.exit(1);});server.listen(port,'127.0.0.1',()=>process.stdout.write('Lixia Typing Garden v3: http://127.0.0.1:'+port+'/\n'));
